image:
  repository: my-jfrog-artifactory.duckdns.org/docker-local/taskflow
  tag: latest
  pullPolicy: Always

replicaCount: 2

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: java-gke-app.duckdns.org
  path: /taskflow

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

serviceAccount:
  name: taskflow-sa
