apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: "taskflow-sa@project-616fef18-15b8-4d6c-8a2.iam.gserviceaccount.com"
